name: Build jupyternim, check display.nim
on: 
  push:
    paths:
      - 'src/**'
      - 'examples/**'
  pull_request:
    branches:
      - master
  workflow_dispatch:    
  schedule:
    - cron: '3 2 1 * *' 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ '1.6.0', 'stable', 'devel' ]
    name: Build on nim ${{ matrix.nim }}
    steps:
      - uses: actions/checkout@master
        
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-stable

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-stable

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1.3.14
        with:
          nim-version: ${{ matrix.nim }}
      - run: nimble build -Y
      - run: nim check src/jupyternimpkg/display.nim
